name: Purge CDN cache

on:
  push:
    branches:
      - master

jobs:
  purge-cache:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@v1
      with:
        args: https://purge.jsdelivr.net/gh/zenfi/partner-integrations@latest/yave/simulator.js
